apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-deployment
  namespace: example
  labels:
    app: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: docker7gm/hello-world-app:v1.0.0
        ports:
        - containerPort: 8080