
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mlapps.demo.go
  resources:
  - tfcanaries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mlapps.demo.go
  resources:
  - tfcanaries/finalizers
  verbs:
  - update
- apiGroups:
  - mlapps.demo.go
  resources:
  - tfcanaries/status
  verbs:
  - get
  - patch
  - update
