# permissions for end users to view tfcanaries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tfcanary-viewer-role
rules:
- apiGroups:
  - mlapps.demo.go
  resources:
  - tfcanaries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mlapps.demo.go
  resources:
  - tfcanaries/status
  verbs:
  - get
