# permissions for end users to edit tfcanaries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tfcanary-editor-role
rules:
- apiGroups:
  - mlapps.demo.go
  resources:
  - tfcanaries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mlapps.demo.go
  resources:
  - tfcanaries/status
  verbs:
  - get
